version: "2"
services:
        orthanc:
                image: osimis/orthanc
                restart: unless-stopped
                ports: ["104:4242", "80:8042"]
                volumes: ["orthanc-storage:/var/lib/orthanc/db:Z"]
                environment:
                        NAME: "My Orthanc"
                        WVB_ENABLED: "true"
                        AC_AUTHENTICATION: "true"
                        AC_REGISTERED_USERS: |
                                {"demo":"demo"}

volumes:
        orthanc-storage:
